# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf4ce1f8a806fbd08dd70a673d61c30ccb22caa72b9ce815cc80be41346a7b8b16d410552f55592998ae5dbe8af8321cd69411b84f8789d69023964e15c8c7eb

test:
  secret_key_base: 35e85ee437a568d9b30a6ebbf0c93cb0f2d574c139761933961f31044116cf1470b93fe410f5fe2c5d3298c65c65e712cead320ab9322529191784774e7583ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
